In [2]:
def fun(x,y,z):
	return x+y*z
fun(z=10,x=20,y=30)

320

In [4]:
import numpy as np
a1= np.arange(10)
a1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
print(np.astype.__doc__)


Copies an array to a specified data type.

This function is an Array API compatible alternative to
`numpy.ndarray.astype`.

Parameters
----------
x : ndarray
    Input NumPy array to cast. ``array_likes`` are explicitly not
    supported here.
dtype : dtype
    Data type of the result.
copy : bool, optional
    Specifies whether to copy an array when the specified dtype matches
    the data type of the input array ``x``. If ``True``, a newly allocated
    array must always be returned. If ``False`` and the specified dtype
    matches the data type of the input array, the input array must be
    returned; otherwise, a newly allocated array must be returned.
    Defaults to ``True``.
device : str, optional
    The device on which to place the returned array. Default: None.
    For Array-API interoperability only, so must be ``"cpu"`` if passed.

    .. versionadded:: 2.1.0

Returns
-------
out : ndarray
    An array having the specified data type.

See Also
--------
ndarray.astype

Exam

In [7]:
a1.astype(float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [8]:
np.astype(a1,int)
a1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a2 = np.arange(5,10)
a1.astype(a2,float)
#will not fix this as you will need to see this error i think to understand 
#i mean one is a module function and another is a instance function/object's function
a2

TypeError: Cannot construct a dtype from an array